In [1]:
import pandas as pd
import numpy as np 

train = pd.read_csv("../2. Prepared Data/train_cleaned.csv")
test = pd.read_csv("../2. Prepared Data/test_cleaned.csv")

X_train = train.loc[:, 'Pclass':]
y_train = train['Survived']
X_test = test.loc[:, 'Pclass':]
X_train.head()

Pclass  Sex     SibSp     Parch      Fare  Embarked  FamilySize  \
0       3    1  0.431350 -0.474326 -0.877591         2    0.057853   
1       1    0  0.431350 -0.474326  1.366380         0    0.057853   
2       3    0 -0.475199 -0.474326 -0.796281         2   -0.561804   
3       1    0  0.431350 -0.474326  1.066796         2    0.057853   
4       3    1 -0.475199 -0.474326 -0.781901         2   -0.561804   

   Cabin_letter  Name_title  Numeric_ticket  Age_bins  
0      0.519424    0.414443               0 -0.489339  
1     -1.932442    0.961091               0  0.671752  
2      0.519424   -1.225498               0 -0.102308  
3     -1.932442    0.961091               1  0.284722  
4      0.519424    0.414443               1  0.284722

In [2]:
#--------------------------------Models Building--------------------------------
from sklearn.model_selection import cross_val_score
#Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter = 2000)
cv = cross_val_score(lr,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.79775281 0.78089888 0.76966292 0.76966292 0.8079096 ]
0.7851774265219322


In [3]:
#Using Naive Bayes
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
cv = cross_val_score(nb,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.7752809  0.75280899 0.76404494 0.80337079 0.8079096 ]
0.7806830444994605


In [4]:
#Using KNN
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
cv = cross_val_score(knn,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.74157303 0.74719101 0.8258427  0.80898876 0.79661017]
0.7840411350219006


In [5]:
#Using Support Vector Classifier
from sklearn.svm import SVC
svc = SVC(probability = True)
cv = cross_val_score(svc,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.83707865 0.82022472 0.80337079 0.80337079 0.84745763]
0.8223005141877738


In [6]:
#Using Random Forest
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state = 1)
cv = cross_val_score(rf,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.79775281 0.76966292 0.87078652 0.76966292 0.8079096 ]
0.80315495461182


In [7]:
#Using Decision Tree
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state = 1)
cv = cross_val_score(dt,X_train,y_train,cv=5)
print(cv)
print(cv.mean())

[0.75280899 0.79213483 0.80898876 0.75280899 0.83050847]
0.7874500095219958


In [8]:
#--------------------------------Model tunning----------------------
from sklearn.model_selection import GridSearchCV 
def reporting(model,classifier):
    print(model)
    print('Best Score: ' + str(classifier.best_score_))
    print('Best Parameters: ' + str(classifier.best_params_))

In [9]:
#SVC Modefiying
svc = SVC(probability = True)
param_grid = {'C':[1,10],
          'gamma':[1,0.1],
          'kernel':['rbf']}
grid_s = GridSearchCV (svc,param_grid = param_grid,cv=5,verbose= True, n_jobs=-1)
best_svc = grid_s.fit(X_train,y_train)
reporting('SVS',best_svc)

Fitting 5 folds for each of 4 candidates, totalling 20 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.


SVS
Best Score: 0.8279311877102774
Best Parameters: {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}


[Parallel(n_jobs=-1)]: Done  18 out of  20 | elapsed:    1.8s remaining:    0.2s
[Parallel(n_jobs=-1)]: Done  20 out of  20 | elapsed:    1.8s finished


In [10]:
#------------------------------Predicting-----------------------------
#Using SVC
svc = SVC( C =  1, gamma= 0.1, kernel= 'rbf',probability = True)
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
final_data = pd.DataFrame({
        "PassengerId":test["PassengerId"],
        "Survived":y_pred
        })


In [11]:
final_data.to_csv('../6. Final/final_data.csv',index = False)

In [12]:
#Using Random Forest
rf = RandomForestClassifier(random_state = 1)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
final_data_rf = pd.DataFrame({
        "PassengerId":test["PassengerId"],
        "Survived":y_pred
        })
final_data_rf.to_csv('../6. Final/final_data_rf.csv',index = False)